version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    reviewers:
      - "iamdrewfortini"
    assignees:
      - "iamdrewfortini"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group updates for better management
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
          - "aws-amplify"
        update-types:
          - "minor"
          - "patch"
      radix-ui:
        patterns:
          - "@radix-ui/*"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    # Auto-merge minor and patch updates
    versioning-strategy: auto

  # Enable GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
